/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class pub_ensemble_hillo_EACMain */

#ifndef _Included_pub_ensemble_hillo_EACMain
#define _Included_pub_ensemble_hillo_EACMain
#ifdef __cplusplus
extern "C" {
#endif

extern"C" __declspec(dllexport) void JNICALL Java_pub_ensemble_hillo_EACMain_initAntiCheat
  (JNIEnv *, jobject);

extern"C" __declspec(dllexport) jint JNICALL Java_pub_ensemble_hillo_EACMain_checkAntiCheat
  (JNIEnv *, jobject,jint,jint);

extern "C" __declspec(dllexport) jint JNICALL Java_pub_ensemble_hillo_EACMain_getHYCCode
  (JNIEnv *, jobject);

extern "C" __declspec(dllexport) jbyteArray JNICALL Java_pub_ensemble_hillo_EACMain_getAuthenticationBody
(JNIEnv*, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
